name: Build and Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Solution Version (x.x.x.x)'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Install Power Platform CLI
      run: |
        pac install latest
    
    - name: Set Solution Version
      run: |
        cd Solution
        pac solution version --strategy gittags
        if [ "${{ github.event.inputs.version }}" != "" ]; then
          pac solution version --version "${{ github.event.inputs.version }}"
        fi
      
    - name: Build Solution
      run: |
        cd Solution
        msbuild /p:configuration=Release /restore
        
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      if: github.ref == 'refs/heads/main'
      with:
        files: Solution/bin/Release/*
        name: Release ${{ github.event.inputs.version || github.sha }}
        tag_name: v${{ github.event.inputs.version || github.run_number }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}